#!/usr/bin/env bash
#
# Reads this sandbox's hidden-service address out of the `anon` daemon and
# renders it into the config the anytoon-connector mounts.
#
#   conf/connector-anytoon.toml           committed, the source of truth,
#                                         [node] endpoints on clearnet
#   conf/.rendered/connector-anytoon.toml generated, gitignored, the SAME file
#                                         with those two endpoints pointed at
#                                         <addr>.anyone — and what compose
#                                         mounts when ANYTOON_CONNECTOR_CONF
#                                         names it (`make up-hs`)
#
# THIS SCRIPT IS THE OPERATOR, not the connector. The connector never reads the
# daemon's hostname file and never speaks its control protocol — connector
# ADR 0070 decision 7 rejects both, because they couple a node's own
# self-description to a sidecar's filesystem layout for a value that never
# changes once generated. So the copying is a step outside the binary. Vendored
# from the anytoon checkout's scripts/hs-address.sh, which does the same job
# with a placeholder template; this one rewrites the two endpoint lines instead,
# so there is only ONE connector config in the tree and it cannot drift.
#
# Idempotent: re-running it against an unchanged address rewrites the same file.
set -euo pipefail

cd "$(dirname "$0")/.."

TEMPLATE="${1:-conf/connector-anytoon.toml}"
RENDERED="${2:-conf/.rendered/connector-anytoon.toml}"
HOSTNAME_FILE="/var/lib/anon/hidden_service/hostname"

die() { printf '\n  %s\n\n' "$*" >&2; exit 1; }

[ -f "$TEMPLATE" ] || die "$TEMPLATE is missing."

# --- Read it out of the daemon ----------------------------------------------
if [ -z "$(docker compose --profile hs ps -q anon 2>/dev/null)" ]; then
  die "The \`anon\` daemon is not running, so no address exists to read.
  \`make up-hs\` starts it first and waits for it. By hand:
      docker compose --profile hs up -d anon
      docker compose --profile hs logs -f anon    (look for Bootstrapped 100%)"
fi

ADDRESS="$(docker compose --profile hs exec -T anon cat "$HOSTNAME_FILE" 2>/dev/null | tr -d '[:space:]' || true)"

if [ -z "$ADDRESS" ]; then
  die "The daemon has not generated an address yet.
  A container that is Up is not a container that has a circuit — wait for
  \`Bootstrapped 100%\` in \`docker compose --profile hs logs anon\` and run this
  again. If it exits immediately, check that conf/anonrc still says
  AgreeToTerms 1."
fi

# An address is 56 characters of the base32 alphabet, then `.anyone` — the same
# shape @toon-protocol/client demands (/^[a-z2-7]+\.anyone$/). Checked here
# rather than left to the client, because a truncated read is the plausible
# failure and it would otherwise surface as an address that parses, loads, and
# resolves to nothing.
if ! printf '%s' "$ADDRESS" | grep -Eqx '[a-z2-7]{56}\.anyone'; then
  die "Read something that is not a hidden-service address: '$ADDRESS'
  Expected 56 characters of [a-z2-7] followed by .anyone.
  A .onion address means the daemon is the OLD v0.4.9.7 release, whose TLD
  every current client refuses — see anon/Dockerfile."
fi

# --- Has it changed? ---------------------------------------------------------
# In a DEPLOYMENT a changed address is an incident (every buyer's configuration
# just went stale, silently). Here it is routine — `make clean` wipes the anon
# volume — so this is a note, not a warning.
if [ -f "$RENDERED" ]; then
  PREVIOUS="$(grep -oE '[a-z2-7]{56}\.anyone' "$RENDERED" | head -1 || true)"
  if [ -n "$PREVIOUS" ] && [ "$PREVIOUS" != "$ADDRESS" ]; then
    printf '\n  note: the address changed (%s -> %s).\n' "$PREVIOUS" "$ADDRESS" >&2
    printf '        expected after `make clean`; the anon volume was wiped.\n\n' >&2
  fi
fi

# --- Render ------------------------------------------------------------------
mkdir -p "$(dirname "$RENDERED")"

grep -q '^http_endpoint = ' "$TEMPLATE" && grep -q '^btp_endpoint = ' "$TEMPLATE" \
  || die "$TEMPLATE has no [node] http_endpoint/btp_endpoint lines to rewrite.
  This script rewrites exactly those two, at the start of a line. If they moved
  or were renamed, fix this script rather than hand-editing the rendered file."

# Port 80 and the default ws port: conf/anonrc forwards virtual port 80 to the
# connector's client edge, so the address needs no port suffix here.
{
  printf '# GENERATED by scripts/hs-address.sh — do not edit, do not commit.\n'
  printf '# conf/connector-anytoon.toml with its [node] endpoints pointed at the\n'
  printf '# hidden-service address the `anon` daemon generated: %s\n' "$ADDRESS"
  printf '# Re-rendered on every `make up-hs`; wiped by `make clean`.\n\n'
  sed -e "s|^http_endpoint = .*|http_endpoint = \"http://${ADDRESS}/ilp\"|" \
      -e "s|^btp_endpoint = .*|btp_endpoint = \"ws://${ADDRESS}/ilp/btp\"|" \
      "$TEMPLATE"
} > "$RENDERED"

grep -q "$ADDRESS" "$RENDERED" || die "rendering $RENDERED did not substitute the address."

printf '\n  %s\n\n' "$ADDRESS"
printf '  rendered into %s\n' "$RENDERED"
printf '  buyers reach the issuer path at:  http://%s/ilp\n' "$ADDRESS"
printf '  and its settlement chain at:      http://%s:8545\n\n' "$ADDRESS"
